# .github/workflows/mobile.yml

name: Build Expo Mobile App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build Expo Web App (can be used for preview)
        run: |
          npm install -g expo
          expo install
          expo build:web

      # Optional: EAS Build (requires EAS secret and login)
      # - name: 🧪 EAS Build
      #   run: |
      #     npm install -g eas-cli
      #     eas build --platform all
